"""On-disk layout for the server.

Application data (session metadata/timing, settings, jobs, reviews, and the
derived index) lives below ``MEETING_NOTES_DATA`` (default ``/data``), while
recording artifacts live below optional ``MEETING_NOTES_MEDIA`` (defaulting to
the data root for backwards compatibility). Session and job ids arrive over
the network (session ids from the recorder client, job ids echoed back to it),
so every id that becomes part of a filesystem path is validated first:
something like ``../../etc/passwd`` must never be able to walk out of either
root.

Track audio is written with random-access seeks keyed by absolute frame
offset, not append-only, because the wire protocol is explicitly designed to
let a reconnecting client resend from its last acknowledged point without
regard for arrival order (see ``meeting_notes.wire``'s header comment). A
sidecar "ranges" file records which byte ranges of the ``.raw`` file have
actually been written (as opposed to being an unwritten hole that happens to
read back as zero, i.e. silence), so we can always answer "what is the
longest contiguous prefix received so far" -- that number is exactly what the
server acks, and what lets a resuming client know where to pick up.
"""

from __future__ import annotations

import json
import logging
import os
import re
import shutil
import tempfile
import threading
import time
import uuid
from datetime import datetime
from pathlib import Path
from typing import List, Optional

from .. import wire
from . import board as board_mod
from . import index as index_mod

# Anything that isn't one path segment is rejected outright. Session and job
# ids are generated by us (uuid4 hex) or supplied by the recorder client, and
# either way they end up interpolated straight into filesystem paths, so this
# is the one gate that has to hold even against an actively hostile client.
logger = logging.getLogger("meeting_notes.server.store")

_SAFE_ID = re.compile(r"^[A-Za-z0-9._-]+$")


_WINDOWS_RESERVED = frozenset(
    ["CON", "PRN", "AUX", "NUL"]
    + [f"COM{i}" for i in range(1, 10)]
    + [f"LPT{i}" for i in range(1, 10)]
)


def is_safe_id(value: str) -> bool:
    """True if ``value`` is safe to use as a single path component.

    Rejects empty strings, ``.``/``..``, anything containing a path separator
    (forward OR back slash -- this may run on a Windows dev box), and NUL,
    which some filesystems treat specially and Python otherwise reports a
    unicode error for.
    """
    if not value or value in (".", ".."):
        return False
    if "/" in value or "\\" in value or "\0" in value:
        return False
    # Most filesystems cap a single component at 255 bytes, and these ids get
    # suffixes appended (".timing.jsonl"), so leave headroom. Without a cap a
    # caller can push writes into an OSError instead of a clean 400.
    if len(value) > 128:
        return False
    # Reserved device names on Windows: "con.raw" is not a file there. The
    # server normally runs in Linux Docker, but it is plain Python and someone
    # will eventually run it natively on Windows.
    if value.split(".")[0].upper() in _WINDOWS_RESERVED:
        return False
    return bool(_SAFE_ID.match(value))


# Error text on a job that a newer job for the same session replaced; such a
# job is bookkeeping and never counts as the session's "latest" job.
JOB_SUPERSEDED_ERROR = "superseded"


def is_superseded_job(job: dict) -> bool:
    return bool(job.get("superseded")) or job.get("error") == JOB_SUPERSEDED_ERROR


# Deleted meetings stay recoverable this long before the retention sweep
# removes them for good (see ``Store.purge_expired_trash``).
TRASH_RETENTION_DAYS = 30
_SECONDS_PER_DAY = 86400.0


class TrashConflict(RuntimeError):
    """A meeting can't be restored because its id is live again."""


class InvalidId(ValueError):
    """A session or job id failed path-safety validation."""


def _check_id(value: str, kind: str) -> str:
    if not is_safe_id(value):
        raise InvalidId(f"invalid {kind} id: {value!r}")
    return value


def resolve_data_root(data_root: Optional[str] = None) -> Path:
    """Pick the directory everything is stored under.

    Preference order: an explicit override (tests pass one so each test gets
    an isolated store), then ``MEETING_NOTES_DATA``, then ``/data`` (the
    Docker volume mountpoint). If that root can't actually be created/written
    to -- e.g. running this outside Docker with no ``/data`` and no
    permission to make it -- fall back to a temp directory rather than
    failing to start, so `pytest` and a bare `uvicorn` run locally both work
    with zero configuration.
    """
    candidate = data_root or os.environ.get("MEETING_NOTES_DATA") or "/data"
    path = Path(candidate)
    try:
        path.mkdir(parents=True, exist_ok=True)
        probe = path / f".write-probe-{os.getpid()}"
        probe.write_text("")
        probe.unlink()
        return path.resolve()
    except OSError:
        fallback = Path(tempfile.mkdtemp(prefix="meeting-notes-data-"))
        return fallback


def resolve_media_root(media_root: Optional[str] = None, data_root: Optional[Path] = None) -> Path:
    """Resolve the durable recording/media root.

    ``MEETING_NOTES_MEDIA`` is intentionally optional: older deployments had
    one ``MEETING_NOTES_DATA`` volume and must continue to work unchanged.
    ``MEETING_NOTES_AUDIO`` and ``MEETING_NOTES_RECORDINGS`` are accepted as
    aliases for operators who used those names in an earlier deployment.
    """
    configured = (
        media_root
        or os.environ.get("MEETING_NOTES_MEDIA")
        or os.environ.get("MEETING_NOTES_AUDIO")
        or os.environ.get("MEETING_NOTES_RECORDINGS")
    )
    path = Path(configured) if configured else (data_root or resolve_data_root())
    try:
        path.mkdir(parents=True, exist_ok=True)
        probe = path / f".write-probe-{os.getpid()}"
        probe.write_text("")
        probe.unlink()
        return path.resolve()
    except OSError:
        # An explicitly configured media path is expected to be durable.  If
        # its mount is missing or unwritable, starting against a temporary
        # directory could migrate existing recordings off durable storage and
        # lose them on restart.  Fail closed so the operator can repair the
        # mount without any audio being moved.
        if configured:
            raise
        return Path(tempfile.mkdtemp(prefix="meeting-notes-media-"))


def _atomic_write_json(path: Path, payload) -> None:
    """Write JSON so a reader never sees a half-written file.

    The job worker thread and request handlers both touch job records
    concurrently; write-to-temp-then-rename makes every read see either the
    old content or the new content, never a torn mix of both.
    """
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp_name = tempfile.mkstemp(dir=str(path.parent), prefix=".tmp-", suffix=".json")
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as fh:
            json.dump(payload, fh, indent=2)
        for attempt in range(5):
            try:
                os.replace(tmp_name, path)
                break
            except PermissionError:
                if attempt == 4:
                    raise
                # Windows indexing/antivirus can briefly retain a handle to
                # the old file. Atomic replacement is still the right write;
                # retry the transient sharing violation instead of failing a
                # recording job.
                time.sleep(0.01 * (attempt + 1))
    except BaseException:
        try:
            os.unlink(tmp_name)
        except OSError:
            pass
        raise


def _read_json(path: Path):
    """Read JSON while tolerating transient Windows sharing violations."""
    for attempt in range(5):
        try:
            return json.loads(path.read_text(encoding="utf-8"))
        except PermissionError:
            if attempt == 4:
                raise
            time.sleep(0.01 * (attempt + 1))


def _merge_ranges(ranges: List[List[int]], start: int, end: int) -> List[List[int]]:
    """Insert ``[start, end)`` into a sorted, merged list of half-open ranges."""
    if start >= end:
        return ranges
    out: List[List[int]] = []
    placed = False
    for lo, hi in ranges:
        if hi < start:
            out.append([lo, hi])
        elif end < lo:
            if not placed:
                out.append([start, end])
                placed = True
            out.append([lo, hi])
        else:
            # Overlaps or touches the new range -- merge instead of appending,
            # which is what makes writing the same offset twice (or two
            # adjacent chunks in either order) collapse into one interval
            # instead of accumulating duplicate/adjacent entries forever.
            start = min(start, lo)
            end = max(end, hi)
    if not placed:
        out.append([start, end])
    return out


def _contiguous_prefix(ranges: List[List[int]]) -> int:
    if ranges and ranges[0][0] == 0:
        return ranges[0][1]
    return 0


def _parse_created_timestamp(value) -> Optional[float]:
    """Parse a session meta's ``created``/``date`` field into a unix
    timestamp, for sorting/paginating the index by recency.

    Accepts a bare number (already a timestamp), or an ISO 8601 string
    (``"2026-09-20"`` or with a time component). Anything else -- missing,
    unparseable -- returns ``None`` so the caller falls back to the session
    directory's mtime rather than sorting a garbage value as if it were real.
    """
    if value is None:
        return None
    if isinstance(value, (int, float)):
        return float(value)
    if isinstance(value, str):
        text = value.strip()
        if not text:
            return None
        try:
            return float(text)
        except ValueError:
            pass
        try:
            return datetime.fromisoformat(text.replace("Z", "+00:00")).timestamp()
        except ValueError:
            return None
    return None


def _extract_transcript_text(json_text: str) -> str:
    """Pull just the spoken text out of a rendered transcript's JSON string,
    for the full-text search index (see index.py's ``transcript_text``
    table). Anything malformed is treated as "nothing to index" rather than
    raised -- a transcript that failed to parse here still exists fine as a
    download, it just won't be found by search.
    """
    try:
        payload = json.loads(json_text or "{}")
    except json.JSONDecodeError:
        return ""
    segments = payload.get("segments") if isinstance(payload, dict) else None
    if not isinstance(segments, list):
        return ""
    return "\n".join(
        str(seg.get("text", "")) for seg in segments if isinstance(seg, dict) and seg.get("text")
    )


class Store:
    """Owns one data root and every read/write against it."""

    def __init__(self, data_root: Optional[str] = None, media_root: Optional[str] = None):
        self.root = resolve_data_root(data_root)
        self.media_root = resolve_media_root(media_root, self.root)
        # Metadata/timing are application data and remain on the backup volume;
        # only the recording artifacts live below the media volume.
        self.sessions_dir = self.root / "sessions"
        self.media_sessions_dir = self.media_root / "sessions"
        # Migrate the old single-volume layout without moving session.json or
        # timing logs. This keeps searchable metadata and transcripts backed up
        # while removing audio from the app-data backup.
        legacy_sessions = self.sessions_dir
        if self.media_root != self.root and legacy_sessions.exists():
            self._migrate_legacy_audio(legacy_sessions)
        self.jobs_dir = self.root / "jobs"
        self.reviews_dir = self.root / "reviews"
        # "Recently deleted": one folder per trashed meeting holding its
        # session dir, job/review files and a trash.json record; the audio
        # goes to the matching folder on the media volume (see trash_session).
        # Both live outside ``sessions/`` so nothing that walks live meetings
        # (reindex, migration, retention) can see them.
        self.trash_dir = self.root / "trash" / "sessions"
        self.media_trash_dir = self.media_root / "trash" / "media"
        self.sessions_dir.mkdir(parents=True, exist_ok=True)
        self.media_sessions_dir.mkdir(parents=True, exist_ok=True)
        self.jobs_dir.mkdir(parents=True, exist_ok=True)
        self.reviews_dir.mkdir(parents=True, exist_ok=True)
        # One lock per (session, track) audio file, so writers of different
        # tracks/sessions never block each other, but the read-modify-write
        # cycle over a single track's ranges sidecar (below) can't race with
        # itself. A meeting has at most a handful of tracks, so a dict of
        # small locks is plenty -- no need for anything fancier.
        self._locks_guard = threading.Lock()
        self._locks: dict = {}
        # Session metadata is updated by uploads, finalization, and explicit
        # user renames.  Atomic file replacement prevents torn JSON, but not
        # lost read-modify-write updates, so each session has its own reentrant
        # lock for metadata mutations.
        self._session_meta_locks_guard = threading.Lock()
        self._session_meta_locks: dict = {}
        self._jobs_lock = threading.Lock()
        self._reviews_lock = threading.RLock()
        # Observers of "review_completed" / "session_renamed" (the Notion export
        # registers here). They run after the write, must be quick, and can
        # never fail the caller.
        self._listeners: dict = {}

        # The index (index.py) is a read-optimization derived entirely from
        # what's on disk -- see that module's docstring. If its file doesn't
        # exist yet (a fresh data root, or an upgrade from a version with no
        # index), rebuild it from disk once, right now, rather than starting
        # up with an empty index that quietly hides every session already
        # recorded until someone notices and reindexes by hand.
        index_path = self.root / "index.sqlite"
        needs_rebuild = not index_path.exists()
        self.index = index_mod.Index(index_path)
        if needs_rebuild:
            self.reindex()
        else:
            # Existing deployments gain the review-status table during an
            # index migration.  Populate it once at startup; list polling
            # itself remains entirely SQLite-backed.
            self._reindex_review_statuses()

    def _migrate_legacy_audio(self, legacy_sessions: Path) -> None:
        """Move only audio artifacts out of a pre-split sessions tree."""
        self.media_sessions_dir.mkdir(parents=True, exist_ok=True)
        audio_patterns = ("*.wav", "*.raw", "*.ranges.json", "source.*", ".upload-*")
        for legacy_dir in sorted(legacy_sessions.iterdir()):
            if not legacy_dir.is_dir() or not is_safe_id(legacy_dir.name):
                continue
            target = self.media_sessions_dir / legacy_dir.name
            target.mkdir(parents=True, exist_ok=True)
            for pattern in audio_patterns:
                for source in legacy_dir.glob(pattern):
                    destination = target / source.name
                    if not source.is_file():
                        continue
                    temporary = destination.with_name(
                        f".migrate-{destination.name}-{uuid.uuid4().hex}.tmp"
                    )
                    try:
                        # Always copy from the authoritative legacy source,
                        # even if a prior interrupted migration left a partial
                        # destination. Promotion is atomic; only then remove
                        # the original. Any failure aborts startup with the
                        # durable source still intact.
                        shutil.copy2(source, temporary)
                        os.replace(temporary, destination)
                        source.unlink()
                    except BaseException:
                        try:
                            temporary.unlink()
                        except OSError:
                            pass
                        raise

    # -- paths -----------------------------------------------------------

    def session_dir(self, session_id: str) -> Path:
        _check_id(session_id, "session")
        return self.sessions_dir / session_id

    def media_session_dir(self, session_id: str) -> Path:
        _check_id(session_id, "session")
        return self.media_sessions_dir / session_id

    def ensure_session_dir(self, session_id: str) -> Path:
        d = self.session_dir(session_id)
        d.mkdir(parents=True, exist_ok=True)
        return d

    def ensure_media_session_dir(self, session_id: str) -> Path:
        d = self.media_session_dir(session_id)
        d.mkdir(parents=True, exist_ok=True)
        return d

    def _track_track_check(self, track: str) -> str:
        # Tracks come from wire.TRACKS, a closed set, but still validate --
        # they land in a filename same as session/job ids do.
        return _check_id(track, "track")

    def track_raw_path(self, session_id: str, track: str) -> Path:
        return self.media_session_dir(session_id) / f"{self._track_track_check(track)}.raw"

    def track_wav_path(self, session_id: str, track: str) -> Path:
        return self.media_session_dir(session_id) / f"{self._track_track_check(track)}.wav"

    def track_timing_path(self, session_id: str, track: str) -> Path:
        return self.session_dir(session_id) / f"{self._track_track_check(track)}.timing.jsonl"

    def _ranges_path(self, session_id: str, track: str) -> Path:
        return self.media_session_dir(session_id) / f"{self._track_track_check(track)}.ranges.json"

    def session_meta_path(self, session_id: str) -> Path:
        return self.session_dir(session_id) / "session.json"

    def uploaded_source_path(self, session_id: str) -> Optional[Path]:
        """Return a normalized/uploaded source file, if this is an upload.

        Uploads are normalized to ``system.wav`` before a job is queued, but
        retaining this helper gives callers a single safe way to discover a
        source during migration and makes future container formats possible.
        """
        session_dir = self.media_session_dir(session_id)
        for path in sorted(session_dir.glob("source.*")):
            if path.is_file():
                return path
        return None

    @staticmethod
    def _pipeline(meta: dict, jobs: list) -> dict:
        def _number(value, fallback=0.0):
            try:
                return float(value)
            except (TypeError, ValueError):
                return fallback

        def _integer(value, fallback=0):
            try:
                return int(value)
            except (TypeError, ValueError):
                return fallback

        upload = meta.get("upload") if isinstance(meta.get("upload"), dict) else {}
        latest = next((j for j in jobs if not is_superseded_job(j)), None)
        if latest is None and jobs:
            latest = jobs[0]
        job_state = latest.get("state") if latest else None
        job_progress = latest.get("progress") if latest else 0.0
        if upload.get("state") == "error":
            upload_state = "error"
        elif upload.get("state") in ("pending", "uploading"):
            upload_state = upload.get("state")
        else:
            upload_state = "complete" if upload else ("complete" if latest else "pending")
        if job_state == wire.JobState.DONE:
            transcription_state = "complete"
        elif job_state == wire.JobState.ERROR:
            transcription_state = "error"
        elif job_state == wire.JobState.RUNNING:
            transcription_state = "transcribing"
        elif job_state == wire.JobState.QUEUED:
            transcription_state = "pending"
        else:
            transcription_state = "pending"
        return {
            "upload": {
                "state": upload_state,
                "percent": round(_number(upload.get("percent", 100.0 if upload_state == "complete" else 0.0)), 2),
                "bytes_received": _integer(upload.get("bytes_received", 0) or 0),
                "bytes_total": _integer(upload.get("bytes_total", 0) or 0),
            },
            "transcription": {
                "state": transcription_state,
                "percent": round(_number(job_progress or 0.0) * 100.0, 2),
                "job_id": latest.get("job_id") if latest else None,
                "error": latest.get("error") if latest else None,
            },
            "state": transcription_state if upload_state == "complete" else upload_state,
        }

    def job_path(self, job_id: str) -> Path:
        _check_id(job_id, "job")
        return self.jobs_dir / f"{job_id}.json"

    def job_transcript_path(self, job_id: str) -> Path:
        _check_id(job_id, "job")
        return self.jobs_dir / f"{job_id}.transcript.json"

    def review_path(self, review_id: str) -> Path:
        _check_id(review_id, "review")
        return self.reviews_dir / f"{review_id}.json"

    # -- session meta ------------------------------------------------------

    def _session_meta_lock_for(self, session_id: str) -> threading.RLock:
        _check_id(session_id, "session")
        with self._session_meta_locks_guard:
            lock = self._session_meta_locks.get(session_id)
            if lock is None:
                lock = threading.RLock()
                self._session_meta_locks[session_id] = lock
            return lock

    def _read_session_meta_unlocked(self, session_id: str) -> dict:
        path = self.session_meta_path(session_id)
        if not path.exists():
            return {}
        return _read_json(path)

    def _write_session_meta_unlocked(self, session_id: str, meta: dict) -> None:
        self.ensure_session_dir(session_id)
        _atomic_write_json(self.session_meta_path(session_id), meta)
        self._index_upsert_session(session_id)

    def write_session_meta(self, session_id: str, meta: dict) -> None:
        with self._session_meta_lock_for(session_id):
            self._write_session_meta_unlocked(session_id, meta)

    def read_session_meta(self, session_id: str) -> dict:
        with self._session_meta_lock_for(session_id):
            return self._read_session_meta_unlocked(session_id)

    def update_session_meta(self, session_id: str, update) -> dict:
        """Atomically apply a metadata mutation and refresh its index row.

        ``update`` receives the current metadata and may mutate it in place
        or return a replacement dictionary.  Use this for partial changes so
        a concurrent upload/finalize write cannot discard a user rename.
        """
        with self._session_meta_lock_for(session_id):
            meta = self._read_session_meta_unlocked(session_id)
            updated = update(meta)
            if updated is None:
                updated = meta
            if not isinstance(updated, dict):
                raise ValueError("session metadata update must produce an object")
            self._write_session_meta_unlocked(session_id, updated)
            return updated

    def add_listener(self, event: str, fn) -> None:
        self._listeners.setdefault(event, []).append(fn)

    def announce_derived(self, kind: str, sources, results) -> None:
        """Tell listeners (the Notion export) that ``sources`` were replaced by ``results`` through a combine,
        split or the undo of one. Never raises."""
        self._notify("sessions_derived", kind, list(sources), list(results))

    def _notify(self, event: str, *args) -> None:
        for fn in list(self._listeners.get(event, ())):
            try:
                fn(*args)
            except Exception:  # noqa: BLE001 - an observer must never break the write it observes
                logger.exception("%s listener failed", event)

    def rename_session(self, session_id: str, name: str) -> dict:
        """Update the user-owned canonical name for a saved meeting."""
        _check_id(session_id, "session")
        if not self.session_exists(session_id):
            raise ValueError(f"session does not exist: {session_id}")
        meta = self.update_session_meta(
            session_id, lambda meta: meta | {"name": name, "name_updated_at": time.time()}
        )
        self._notify("session_renamed", session_id)
        return meta

    def session_exists(self, session_id: str) -> bool:
        return self.session_dir(session_id).exists()

    # -- index -------------------------------------------------------------
    #
    # Everything below reads/writes the SQLite index (index.py) rather than
    # the filesystem, so the web UI and JSON API can list/search/paginate
    # sessions without a directory walk scaling with how many meetings have
    # ever been recorded. See index.py's module docstring for the full
    # rationale; the methods below are the only place Store talks to it.

    def _index_upsert_session(self, session_id: str) -> None:
        """Recompute one session's index row from what's actually on disk.

        Scoped to a single session -- O(that session's own files), never
        O(every session) -- so calling this from every write (meta saved, a
        job created/updated, a transcript written, audio deleted) stays cheap
        no matter how large the data root has grown. Bulk rebuilds
        (``reindex``) just call this once per session directory.
        """
        session_dir = self.session_dir(session_id)
        if not session_dir.exists():
            self.index.delete_session(session_id)
            return

        meta = self.read_session_meta(session_id)
        # started_wall first: it is a real epoch stamped by the recorder.
        # "created" is the recorder's LOCAL wall time with no zone, and
        # parsing that on a UTC server (every Docker container) placed
        # sessions hours off -- seen on a real run, 4 h early from a
        # machine on UTC-4.
        created = _parse_created_timestamp(meta.get("started_wall"))
        if created is None:
            created = _parse_created_timestamp(meta.get("created") or meta.get("date"))
        if created is None:
            try:
                created = session_dir.stat().st_mtime
            except OSError:
                created = time.time()
        name = str(meta.get("name") or session_id)
        duration_sec = meta.get("duration_sec")
        device = str(meta.get("device") or "")
        platform_name = str(meta.get("platform") or "")
        if not device:
            devices = sorted(
                {
                    str(info.get("device"))
                    for info in (meta.get("tracks") or {}).values()
                    if isinstance(info, dict) and info.get("device")
                }
            )
            device = ", ".join(devices)

        has_audio = False
        audio_bytes = 0
        media_dir = self.media_session_dir(session_id)
        for pattern in ("*.wav", "*.raw"):
            for p in media_dir.glob(pattern):
                has_audio = True
                try:
                    audio_bytes += p.stat().st_size
                except OSError:
                    pass

        jobs = self.index.jobs_for_session(session_id)  # newest first
        # A superseded job (see JobQueue.resume_interrupted) is bookkeeping,
        # not the session's state: never let it be the "latest" job.
        latest = next((j for j in jobs if j.get("error") != JOB_SUPERSEDED_ERROR), None)
        if latest is None and jobs:
            latest = jobs[0]

        self.index.upsert_session(
            session_id=session_id,
            name=name,
            created=created,
            duration_sec=duration_sec,
            device=device or None,
            platform=platform_name or None,
            has_audio=has_audio,
            audio_bytes=audio_bytes,
            latest_job_id=latest["job_id"] if latest else None,
            latest_state=latest["state"] if latest else None,
            latest_progress=latest["progress"] if latest else None,
            latest_error=latest["error"] if latest else None,
            updated=time.time(),
        )

    def list_sessions(
        self,
        *,
        q: Optional[str] = None,
        state: Optional[str] = None,
        page: int = 1,
        per_page: int = 50,
    ) -> dict:
        """Paginated session listing, newest first: ``{items, total, page,
        per_page}``. Backed entirely by the index -- never touches the
        filesystem, regardless of how many sessions exist (see
        ``tests/test_index.py``'s scale test)."""
        # "M-0142" style queries also match board numbers (derived from the id).
        digits = board_mod.parse_board_query(q)
        extra_ids = (
            board_mod.matching_ids(self.index.all_session_ids(), digits) if digits else None
        )
        result = self.index.query_sessions(
            q=q, state=state, page=page, per_page=per_page, extra_ids=extra_ids
        )
        items = result.get("items", [])
        # Keep the index query cheap while exposing the richer lifecycle
        # object expected by Home/saved-transcriptions clients. Metadata and
        # jobs are already bounded to the returned page.
        for item in items:
            session_id = item.get("session_id")
            if not session_id:
                continue
            meta = self.read_session_meta(session_id)
            jobs = self.jobs_for_session(session_id)
            item["pipeline"] = self._pipeline(meta, jobs)
            item["board"] = board_mod.board_number(session_id)
        # Library-wide (ignores q/state), so Home can show an exact count.
        result["audio_total"] = self.index.count_with_audio()
        return result

    def session_index_row(self, session_id: str) -> Optional[dict]:
        _check_id(session_id, "session")
        return self.index.get_session(session_id)

    def session_detail(self, session_id: str) -> Optional[dict]:
        """Everything the transcript page/API needs for one session: its raw
        meta, every job (newest first), and the latest successful job's
        transcript, if any. Scoped to one session, so -- unlike
        ``list_sessions`` -- reading a few files here is fine; there is no
        "thousands of these at once" case for a single-session detail view.
        """
        _check_id(session_id, "session")
        if not self.session_dir(session_id).exists():
            return None
        meta = self.read_session_meta(session_id)
        jobs = self.jobs_for_session(session_id)
        row = self.index.get_session(session_id) or {}
        done_job = next((j for j in jobs if j.get("state") == wire.JobState.DONE), None)

        segments = None
        markdown = None
        transcript_job_id = None
        if done_job is not None:
            transcript = self.read_transcript(done_job["job_id"])
            if transcript is not None:
                transcript_job_id = done_job["job_id"]
                markdown = transcript.get("markdown")
                try:
                    payload = json.loads(transcript.get("json") or "{}")
                except json.JSONDecodeError:
                    payload = {}
                segments = payload.get("segments") if isinstance(payload, dict) else None

        return {
            "session_id": session_id,
            "board": board_mod.board_number(session_id),
            "meta": meta,
            "jobs": jobs,
            "has_audio": bool(row.get("has_audio")),
            "audio_bytes": row.get("audio_bytes") or 0,
            "transcript_job_id": transcript_job_id,
            "segments": segments,
            "markdown": markdown,
            "review": self.review_for_session(session_id),
            "pipeline": self._pipeline(meta, jobs),
        }

    def latest_done_job(self, session_id: str) -> Optional[dict]:
        for job in self.jobs_for_session(session_id):
            if job.get("state") == wire.JobState.DONE:
                return job
        return None

    def delete_session_audio(self, session_id: str) -> int:
        """Remove a session's audio (wav/raw + the ranges sidecar) but keep
        ``session.json`` and the timing logs -- retention only ever throws
        away the recording, never the record that a meeting happened or the
        transcript produced from it. Returns bytes freed, purely for the
        retention worker's log line.
        """
        _check_id(session_id, "session")
        session_dir = self.media_session_dir(session_id)
        freed = 0
        if session_dir.exists():
            for pattern in ("*.wav", "*.raw", "*.ranges.json", "source.*", ".upload-*"):
                for p in session_dir.glob(pattern):
                    try:
                        freed += p.stat().st_size
                    except OSError:
                        pass
                    try:
                        p.unlink()
                    except OSError:
                        pass
        self._index_upsert_session(session_id)
        return freed

    def delete_session(self, session_id: str) -> None:
        """Remove a session entirely: its directory, every job that ever ran
        against it, and their transcripts. Unlike ``delete_session_audio``,
        this is a full, irreversible removal -- it's the "delete session"
        button, not the retention sweep.
        """
        _check_id(session_id, "session")
        with self._reviews_lock:
            for review in self.list_reviews(session_id=session_id):
                try:
                    self.review_path(review["review_id"]).unlink()
                except OSError:
                    pass
        for job in self.jobs_for_session(session_id):
            job_id = job["job_id"]
            for path in (self.job_path(job_id), self.job_transcript_path(job_id)):
                try:
                    path.unlink()
                except OSError:
                    pass
        session_dir = self.session_dir(session_id)
        if session_dir.exists():
            shutil.rmtree(session_dir)
        media_session_dir = self.media_session_dir(session_id)
        if media_session_dir.exists():
            shutil.rmtree(media_session_dir)
        self.index.delete_session(session_id)

    # -- recently deleted (trash) ------------------------------------------
    #
    # Deleting a meeting MOVES everything that belongs to it, so nothing is
    # lost and nothing that scans live data can still see it:
    #   <data>/trash/sessions/<id>/session/      the session dir (session.json, timing logs)
    #   <data>/trash/sessions/<id>/jobs/         its job + transcript files
    #   <data>/trash/sessions/<id>/reviews/      its meeting-notes reviews
    #   <data>/trash/sessions/<id>/trash.json    the record (deleted_at, name, ...)
    #   <media>/trash/media/<id>/                its audio
    # Moving (rather than a ``deleted`` flag in session.json) means the index,
    # job worker, review queue, retention sweep, agent API and search all see
    # exactly what a permanently-deleted meeting looks like without each of
    # them needing a filter that a future change could forget. Restore moves
    # the pieces back and re-indexes; the index is only a cache either way.

    def _trash_entry(self, session_id: str) -> Path:
        _check_id(session_id, "session")
        return self.trash_dir / session_id

    def _media_trash_entry(self, session_id: str) -> Path:
        _check_id(session_id, "session")
        return self.media_trash_dir / session_id

    def is_trashed(self, session_id: str) -> bool:
        return (self._trash_entry(session_id) / "trash.json").is_file()

    @staticmethod
    def _tree_size(path: Path) -> int:
        if path.is_file():
            try:
                return path.stat().st_size
            except OSError:
                return 0
        total = 0
        for p in path.rglob("*"):
            try:
                if p.is_file():
                    total += p.stat().st_size
            except OSError:
                pass
        return total

    def trash_session(
        self, session_id: str, *, source: str = "api", now: Optional[float] = None
    ) -> Optional[dict]:
        """Move a meeting to "Recently deleted". Returns its trash record, or
        ``None`` if there is no such meeting. Reversible via ``restore_session``
        until ``purge_expired_trash`` removes it after ``TRASH_RETENTION_DAYS``.
        """
        _check_id(session_id, "session")
        now = time.time() if now is None else now
        with self._session_meta_lock_for(session_id), self._reviews_lock, self._jobs_lock:
            session_dir = self.session_dir(session_id)
            if not session_dir.exists():
                return None
            meta = self._read_session_meta_unlocked(session_id)
            jobs = self.jobs_for_session(session_id)
            reviews = self.list_reviews(session_id=session_id)
            # A job still queued/running can't finish once its meeting is
            # gone; record that on the job so a later restore is consistent
            # (the audio is kept, so the owner can simply retranscribe).
            for job in jobs:
                if job.get("state") in (wire.JobState.QUEUED, wire.JobState.RUNNING):
                    job["state"] = wire.JobState.ERROR
                    job["error"] = "Interrupted: the meeting was deleted while this was pending."
                    job["progress"] = 1.0
                    _atomic_write_json(self.job_path(job["job_id"]), job)
            media_dir = self.media_session_dir(session_id)
            entry = self._trash_entry(session_id)
            media_entry = self._media_trash_entry(session_id)
            # An id can only be in trash AND live again if something bypassed
            # the restore-on-upload hooks; keep the newer deletion.
            for stale in (entry, media_entry):
                if stale.exists():
                    logger.warning("trash: replacing older trashed copy of %s", session_id)
                    shutil.rmtree(stale, ignore_errors=True)

            audio_bytes = 0
            has_audio = False
            if media_dir.exists():
                for pattern in ("*.wav", "*.raw"):
                    for p in media_dir.glob(pattern):
                        has_audio = True
                        try:
                            audio_bytes += p.stat().st_size
                        except OSError:
                            pass
            record = {
                "session_id": session_id,
                "name": str(meta.get("name") or session_id),
                "created": _parse_created_timestamp(meta.get("started_wall"))
                or _parse_created_timestamp(meta.get("created") or meta.get("date")),
                "duration_sec": meta.get("duration_sec"),
                "deleted_at": now,
                "deleted_via": source,
                "has_audio": has_audio,
                "audio_bytes": audio_bytes,
                "size_bytes": self._tree_size(session_dir)
                + (self._tree_size(media_dir) if media_dir.exists() else 0),
                "job_ids": [j["job_id"] for j in jobs],
                "review_ids": [r["review_id"] for r in reviews if r.get("review_id")],
            }
            moved: list = []  # (src, dst) pairs, for rollback

            def move(src: Path, dst: Path) -> None:
                if not src.exists():
                    return
                dst.parent.mkdir(parents=True, exist_ok=True)
                shutil.move(str(src), str(dst))
                moved.append((src, dst))

            try:
                entry.mkdir(parents=True, exist_ok=True)
                _atomic_write_json(entry / "trash.json", record)
                move(session_dir, entry / "session")
                move(media_dir, media_entry)
                for job in jobs:
                    for path in (self.job_path(job["job_id"]), self.job_transcript_path(job["job_id"])):
                        move(path, entry / "jobs" / path.name)
                for review in reviews:
                    if review.get("review_id"):
                        path = self.review_path(review["review_id"])
                        move(path, entry / "reviews" / path.name)
            except BaseException:
                for src, dst in reversed(moved):
                    try:
                        shutil.move(str(dst), str(src))
                    except OSError:
                        logger.exception("trash: could not roll back %s", dst)
                shutil.rmtree(entry, ignore_errors=True)
                raise
            self.index.delete_session(session_id)
            logger.info("trash: moved meeting %s (%s) to Recently deleted", session_id, source)
            return record

    def _read_trash_record(self, session_id: str) -> Optional[dict]:
        path = self._trash_entry(session_id) / "trash.json"
        if not path.is_file():
            return None
        try:
            value = _read_json(path)
        except (json.JSONDecodeError, OSError):
            return None
        return value if isinstance(value, dict) else None

    def list_trash(self, now: Optional[float] = None) -> List[dict]:
        """Trashed meetings, most recently deleted first."""
        now = time.time() if now is None else now
        items: List[dict] = []
        if not self.trash_dir.exists():
            return items
        for entry in self.trash_dir.iterdir():
            if not entry.is_dir() or not is_safe_id(entry.name):
                continue
            record = self._read_trash_record(entry.name)
            if record is None or not (entry / "session").exists():
                continue
            deleted_at = float(record.get("deleted_at") or 0)
            purge_at = deleted_at + TRASH_RETENTION_DAYS * _SECONDS_PER_DAY
            items.append(
                {
                    "session_id": entry.name,
                    "board": board_mod.board_number(entry.name),
                    "name": record.get("name") or entry.name,
                    "created": record.get("created"),
                    "duration_sec": record.get("duration_sec"),
                    "deleted_at": deleted_at,
                    "deleted_via": record.get("deleted_via"),
                    "purge_at": purge_at,
                    "days_left": max(0, int(-(-(purge_at - now) // _SECONDS_PER_DAY))),
                    "has_audio": bool(record.get("has_audio")),
                    "audio_bytes": record.get("audio_bytes") or 0,
                    "size_bytes": record.get("size_bytes") or 0,
                }
            )
        items.sort(key=lambda item: item["deleted_at"], reverse=True)
        return items

    def restore_session(self, session_id: str) -> Optional[dict]:
        """Put a trashed meeting back exactly as it was and re-index it.
        Returns the trash record, ``None`` if it isn't in trash, and raises
        ``TrashConflict`` if a live meeting already uses the id."""
        _check_id(session_id, "session")
        with self._session_meta_lock_for(session_id), self._reviews_lock, self._jobs_lock:
            record = self._read_trash_record(session_id)
            entry = self._trash_entry(session_id)
            if record is None or not (entry / "session").exists():
                return None
            if self.session_dir(session_id).exists():
                raise TrashConflict(f"a meeting with id {session_id} already exists")
            media_entry = self._media_trash_entry(session_id)
            moved: list = []

            def move(src: Path, dst: Path) -> None:
                if not src.exists():
                    return
                dst.parent.mkdir(parents=True, exist_ok=True)
                shutil.move(str(src), str(dst))
                moved.append((src, dst))

            try:
                move(entry / "session", self.session_dir(session_id))
                live_media = self.media_session_dir(session_id)
                if media_entry.exists():
                    if live_media.exists():
                        # A stray empty dir (or a partial re-stream); never
                        # overwrite anything already there.
                        for child in list(media_entry.iterdir()):
                            if not (live_media / child.name).exists():
                                move(child, live_media / child.name)
                        shutil.rmtree(media_entry, ignore_errors=True)
                    else:
                        move(media_entry, live_media)
                jobs_src = entry / "jobs"
                if jobs_src.exists():
                    for f in list(jobs_src.iterdir()):
                        move(f, self.jobs_dir / f.name)
                reviews_src = entry / "reviews"
                if reviews_src.exists():
                    for f in list(reviews_src.iterdir()):
                        move(f, self.reviews_dir / f.name)
            except BaseException:
                for src, dst in reversed(moved):
                    try:
                        shutil.move(str(dst), str(src))
                    except OSError:
                        logger.exception("trash: could not roll back restore of %s", dst)
                raise
            # Jobs first so the session row picks up its latest job.
            for job_id in record.get("job_ids") or []:
                if is_safe_id(job_id):
                    self._index_job_file(job_id)
            for review_id in record.get("review_ids") or []:
                if is_safe_id(review_id):
                    review = self._read_review_unlocked(review_id)
                    if review:
                        self._index_review_status(review, review_id=review_id)
            self._index_upsert_session(session_id)
            shutil.rmtree(entry, ignore_errors=True)
            logger.info("trash: restored meeting %s", session_id)
            return record

    def restore_if_trashed(self, session_id: str) -> bool:
        """Used before an upload/finalize touches an id: if it is in trash,
        bring it back first so the upload fills the existing meeting."""
        if not self.is_trashed(session_id):
            return False
        return self.restore_session(session_id) is not None

    def purge_trashed(self, session_id: str) -> bool:
        """Permanently remove one trashed meeting (the old full delete)."""
        _check_id(session_id, "session")
        entry = self._trash_entry(session_id)
        media_entry = self._media_trash_entry(session_id)
        if not entry.exists() and not media_entry.exists():
            return False
        shutil.rmtree(entry, ignore_errors=True)
        shutil.rmtree(media_entry, ignore_errors=True)
        return True

    def empty_trash(self) -> int:
        count = 0
        for item in self.list_trash():
            if self.purge_trashed(item["session_id"]):
                count += 1
        return count

    def purge_expired_trash(self, now: Optional[float] = None) -> List[str]:
        """Permanently remove meetings trashed more than ``TRASH_RETENTION_DAYS`` ago."""
        now = time.time() if now is None else now
        purged: List[str] = []
        for item in self.list_trash(now):
            if item["purge_at"] <= now and self.purge_trashed(item["session_id"]):
                purged.append(item["session_id"])
                logger.info(
                    "trash: permanently deleted %s (%s), trashed %.0f days ago",
                    item["session_id"], item["name"], (now - item["deleted_at"]) / _SECONDS_PER_DAY,
                )
        return purged

    def _index_job_file(self, job_id: str) -> None:
        """(Re)index one job from its file on disk, plus its transcript text."""
        job = self.read_job(job_id)
        if not job or not job.get("session_id"):
            return
        now = time.time()
        self.index.upsert_job(
            job_id=job_id,
            session_id=job["session_id"],
            state=job.get("state"),
            progress=job.get("progress"),
            error=job.get("error"),
            created=job.get("created", now),
            updated=now,
        )
        transcript = self.read_transcript(job_id)
        if transcript is not None:
            text = _extract_transcript_text(transcript.get("json", ""))
            if text:
                self.index.set_transcript_text(job["session_id"], text)

    def reindex(self) -> int:
        """Rebuild the SQLite index from what's actually on disk.

        The index is a cache, not the source of truth (see index.py's module
        docstring), so this can always recover from a missing, corrupt, or
        stale database. Runs automatically once, from ``__init__``, when the
        index file doesn't exist yet; also reachable explicitly via
        ``POST /v1/reindex`` (and a button on the settings page) for an
        operator who wants to force a rebuild -- e.g. after restoring the
        data volume from a backup that didn't include index.sqlite.

        Jobs are indexed before sessions so that, by the time each session's
        row is computed, its "latest job" is already in the index -- doing
        it in the other order would leave every session's latest_job_id/state
        null on a fresh rebuild.
        """
        self.index.clear()

        if self.jobs_dir.exists():
            for entry in sorted(self.jobs_dir.iterdir()):
                if not entry.name.endswith(".json") or entry.name.endswith(".transcript.json"):
                    continue
                job_id = entry.stem
                if not is_safe_id(job_id):
                    continue
                self._index_job_file(job_id)

        count = 0
        if self.sessions_dir.exists():
            for entry in sorted(self.sessions_dir.iterdir()):
                if entry.is_dir() and is_safe_id(entry.name):
                    self._index_upsert_session(entry.name)
                    count += 1
        self._reindex_review_statuses()
        return count

    # -- track audio ---------------------------------------------------------

    def _lock_for(self, session_id: str, track: str) -> threading.Lock:
        key = (session_id, track)
        with self._locks_guard:
            lock = self._locks.get(key)
            if lock is None:
                lock = threading.Lock()
                self._locks[key] = lock
            return lock

    def append_pcm(self, session_id: str, track: str, frame_offset: int, pcm: bytes) -> int:
        """Write ``pcm`` at ``frame_offset`` in this track's raw file.

        Returns the highest contiguous frame count from 0 -- i.e. what to ack.
        A write is a plain ``seek`` + ``write``, so re-sending the same offset
        (a reconnect resending unacknowledged data) or sending offsets out of
        order both land in the right place idempotently: writing identical
        bytes to the same range twice is a no-op as far as the *content* goes,
        and the ranges sidecar below (not file size) is what tracks how much
        of the file is real received audio versus an unwritten hole.
        """
        self._track_track_check(track)
        if frame_offset < 0:
            raise ValueError("frame_offset must not be negative")
        if len(pcm) % wire.BYTES_PER_FRAME:
            raise ValueError("pcm payload must contain whole int16 samples")
        n_frames = len(pcm) // wire.BYTES_PER_FRAME
        raw_path = self.track_raw_path(session_id, track)
        raw_path.parent.mkdir(parents=True, exist_ok=True)

        with self._lock_for(session_id, track):
            # 'r+b' needs the file to already exist; create it empty first.
            if not raw_path.exists():
                raw_path.touch()
            byte_offset = frame_offset * wire.BYTES_PER_FRAME
            with open(raw_path, "r+b") as fh:
                fh.seek(byte_offset)
                fh.write(pcm)

            ranges = self._read_ranges(session_id, track)
            if n_frames > 0:
                ranges = _merge_ranges(ranges, frame_offset, frame_offset + n_frames)
                self._write_ranges(session_id, track, ranges)
            return _contiguous_prefix(ranges)

    def contiguous_frames(self, session_id: str, track: str) -> int:
        return _contiguous_prefix(self._read_ranges(session_id, track))

    def read_pcm_range(self, session_id: str, track: str, start_frame: int, end_frame: int) -> bytes:
        """Read PCM for ``[start_frame, end_frame)``. Caller keeps this inside
        the acknowledged contiguous prefix -- there's no promise about what an
        unwritten hole beyond it contains."""
        if end_frame <= start_frame:
            return b""
        raw_path = self.track_raw_path(session_id, track)
        with self._lock_for(session_id, track):
            with open(raw_path, "rb") as fh:
                fh.seek(start_frame * wire.BYTES_PER_FRAME)
                return fh.read((end_frame - start_frame) * wire.BYTES_PER_FRAME)

    def _read_ranges(self, session_id: str, track: str) -> List[List[int]]:
        path = self._ranges_path(session_id, track)
        if not path.exists():
            return []
        try:
            return _read_json(path)
        except (json.JSONDecodeError, OSError):
            return []

    def _write_ranges(self, session_id: str, track: str, ranges: List[List[int]]) -> None:
        # Ranges are a JSON array, not an object, but _atomic_write_json only
        # cares that json.dump can serialize its argument -- it does.
        _atomic_write_json(self._ranges_path(session_id, track), ranges)

    # -- jobs ------------------------------------------------------------

    def create_job(self, session_id: str, settings: Optional[dict] = None) -> str:
        _check_id(session_id, "session")
        job_id = uuid.uuid4().hex
        now = time.time()
        record = {
            "job_id": job_id,
            "session_id": session_id,
            "settings": settings or {},
            "state": wire.JobState.QUEUED,
            "progress": 0.0,
            "error": None,
            # Only ever read back for index ordering (jobs_for_session /
            # list_jobs) -- not part of the wire contract, so adding it here
            # doesn't touch anything that reads a job record over the API.
            "created": now,
        }
        with self._jobs_lock:
            _atomic_write_json(self.job_path(job_id), record)
        self.index.upsert_job(
            job_id=job_id,
            session_id=session_id,
            state=record["state"],
            progress=record["progress"],
            error=record["error"],
            created=now,
            updated=now,
        )
        self._index_upsert_session(session_id)
        return job_id

    def read_job(self, job_id: str) -> Optional[dict]:
        path = self.job_path(job_id)
        if not path.exists():
            return None
        try:
            return _read_json(path)
        except (json.JSONDecodeError, OSError):
            return None

    def update_job(self, job_id: str, **fields) -> None:
        with self._jobs_lock:
            record = self.read_job(job_id)
            if record is None:
                # The job's file is gone: its meeting was deleted or moved to
                # Recently deleted while it ran. Don't resurrect an orphan.
                return
            record.update(fields)
            _atomic_write_json(self.job_path(job_id), record)
        session_id = record.get("session_id")
        now = time.time()
        self.index.upsert_job(
            job_id=job_id,
            session_id=session_id or "",
            state=record.get("state"),
            progress=record.get("progress"),
            error=record.get("error"),
            created=record.get("created", now),
            updated=now,
        )
        if session_id:
            self._index_upsert_session(session_id)

    def write_transcript(self, job_id: str, markdown: str, json_text: str) -> None:
        _check_id(job_id, "job")
        job = self.read_job(job_id)
        if job is None:
            return  # meeting deleted/trashed mid-job
        _atomic_write_json(self.job_transcript_path(job_id), {"markdown": markdown, "json": json_text})
        if job and job.get("session_id"):
            text = _extract_transcript_text(json_text)
            self.index.set_transcript_text(job["session_id"], text)

    def read_transcript(self, job_id: str) -> Optional[dict]:
        path = self.job_transcript_path(job_id)
        if not path.exists():
            return None
        try:
            return _read_json(path)
        except (json.JSONDecodeError, OSError):
            return None

    def list_jobs(self) -> List[dict]:
        """Every job's index row (job_id, session_id, state, progress, error,
        created, updated), newest first -- backed by the index so this scales
        the same way ``list_sessions`` does, without reading every job file
        off disk just to list them.
        """
        return self.index.all_jobs()

    def job_records_on_disk(self) -> List[dict]:
        """Every live job record read straight from ``jobs/`` (not the index).

        The index drops jobs whose session directory is gone, so startup
        recovery (``JobQueue.resume_interrupted``) scans the files instead.
        """
        out = []
        if self.jobs_dir.exists():
            for entry in sorted(self.jobs_dir.iterdir()):
                if not entry.name.endswith(".json") or entry.name.endswith(".transcript.json"):
                    continue
                if not is_safe_id(entry.stem):
                    continue
                record = self.read_job(entry.stem)
                if record is not None and record.get("job_id"):
                    out.append(record)
        return out

    def audio_mtime(self, session_id: str) -> float:
        """Newest modification time of a session's audio files (0.0 if none).

        Used by finalize to tell whether audio arrived after a job was created.
        """
        _check_id(session_id, "session")
        newest = 0.0
        media_dir = self.media_session_dir(session_id)
        if media_dir.exists():
            for pattern in ("*.wav", "*.raw", "source.*"):
                for p in media_dir.glob(pattern):
                    try:
                        newest = max(newest, p.stat().st_mtime)
                    except OSError:
                        pass
        return newest

    def jobs_for_session(self, session_id: str) -> List[dict]:
        """Full job records (including ``settings``) for one session, newest
        first. Reads each job file individually -- fine here since this is
        bounded by how many times ONE session has been (re)transcribed, not
        by how many sessions exist.
        """
        _check_id(session_id, "session")
        rows = self.index.jobs_for_session(session_id)
        out = []
        for row in rows:
            full = self.read_job(row["job_id"])
            if full is not None:
                out.append(full)
        return out

    # -- meeting-note reviews --------------------------------------------

    REVIEW_STATUSES = frozenset(("queued", "running", "done", "error"))
    REVIEW_STALE_SECONDS = 15 * 60

    def _read_review_unlocked(self, review_id: str) -> Optional[dict]:
        path = self.review_path(review_id)
        if not path.exists():
            return None
        try:
            value = _read_json(path)
        except (json.JSONDecodeError, OSError):
            return None
        return value if isinstance(value, dict) else None

    def read_review(self, review_id: str) -> Optional[dict]:
        """Read one persisted meeting-note review, or ``None`` if missing."""
        with self._reviews_lock:
            return self._read_review_unlocked(review_id)

    def list_reviews(self, session_id: Optional[str] = None) -> List[dict]:
        """Return reviews newest-first, optionally restricted to one session."""
        if session_id is not None:
            _check_id(session_id, "session")
        with self._reviews_lock:
            records = []
            for path in self.reviews_dir.glob("*.json"):
                if not is_safe_id(path.stem):
                    continue
                record = self._read_review_unlocked(path.stem)
                if record and (session_id is None or record.get("session_id") == session_id):
                    records.append(record)
            return sorted(records, key=lambda item: item.get("created", 0), reverse=True)

    def review_for_session(self, session_id: str) -> Optional[dict]:
        """Return the newest review for a session, without its full payload."""
        _check_id(session_id, "session")
        reviews = self.list_reviews(session_id=session_id)
        if not reviews:
            return None
        review = reviews[0]
        return {
            key: review.get(key)
            for key in (
                "review_id", "session_id", "transcript_job_id", "status",
                "created", "updated", "claimed_at", "completed_at", "error",
            )
        } | {"summary": (review.get("payload") or {}).get("summary")}

    def _index_review_status(self, review: dict, *, review_id: Optional[str] = None) -> None:
        """Synchronize one valid persisted review's compact list state."""
        session_id = review.get("session_id")
        status = review.get("status")
        review_id = review_id or review.get("review_id")
        if (
            not isinstance(session_id, str)
            or not is_safe_id(session_id)
            or not isinstance(review_id, str)
            or not is_safe_id(review_id)
            or not isinstance(status, str)
            or status not in self.REVIEW_STATUSES
        ):
            return
        try:
            created = float(review.get("created", 0))
        except (TypeError, ValueError):
            created = 0.0
        self.index.upsert_review_status(
            session_id=session_id, review_id=review_id, status=status, created=created
        )

    def _reindex_review_statuses(self) -> None:
        """Rebuild compact review state from review JSON during startup/reindex."""
        with self._reviews_lock:
            self.index.clear_review_statuses()
            for path in self.reviews_dir.glob("*.json"):
                if not is_safe_id(path.stem):
                    continue
                review = self._read_review_unlocked(path.stem)
                if not review:
                    continue
                self._index_review_status(review, review_id=path.stem)

    def latest_review(self, session_id: str) -> Optional[dict]:
        """Alias for callers that use the explicit latest-review wording."""
        _check_id(session_id, "session")
        reviews = self.list_reviews(session_id=session_id)
        return reviews[0] if reviews else None

    @staticmethod
    def _template_fields(template: Optional[dict]) -> dict:
        """The ``{id, name}`` of the note template a review was asked to use.

        ``None`` means "whatever the default is when the job is claimed" (old
        records, and callers that do not care). The name is stored beside the
        id so the notes can still say which note type made them after the template
        is renamed or deleted.
        """
        if not isinstance(template, dict):
            return {"template_id": None, "template_name": None}
        return {
            "template_id": str(template.get("id") or "") or None,
            "template_name": str(template.get("name") or "") or None,
        }

    def create_review(
        self, session_id: str, force: bool = False, template: Optional[dict] = None
    ) -> dict:
        """Queue a review of the latest completed transcript.

        Reviews are deliberately not created for an unfinished or missing
        transcript.  Unless ``force`` is set, the newest queued/running/done
        review is returned so repeated button clicks remain idempotent (the
        existing review keeps its own template; ``template`` only applies to a
        review that is actually created). ``template`` is ``{"id", "name"}``.
        """
        _check_id(session_id, "session")
        if not self.session_exists(session_id):
            raise ValueError(f"session does not exist: {session_id}")
        transcript_job = self.latest_done_job(session_id)
        if transcript_job is None or self.read_transcript(transcript_job["job_id"]) is None:
            raise ValueError("session has no completed transcript")
        with self._reviews_lock:
            if not force:
                for review in self.list_reviews(session_id=session_id):
                    if (
                        review.get("transcript_job_id") == transcript_job["job_id"]
                        and review.get("status") in ("queued", "running", "done")
                    ):
                        self._index_review_status(review)
                        return review
            now = time.time()
            review = {
                "review_id": uuid.uuid4().hex,
                "session_id": session_id,
                "transcript_job_id": transcript_job["job_id"],
                "status": "queued",
                "created": now,
                "updated": now,
                "claimed_at": None,
                "completed_at": None,
                "error": None,
                "payload": None,
                # A user may name the summary independently of the meeting.
                # Keep that choice through retry/regeneration, where payload
                # is deliberately cleared and later replaced by AI output.
                "title_override": None,
                **self._template_fields(template),
            }
            _atomic_write_json(self.review_path(review["review_id"]), review)
            self._index_review_status(review)
            return review

    def claim_next_review(self, stale_after: float = REVIEW_STALE_SECONDS) -> Optional[dict]:
        """Atomically claim the oldest queued review.

        A worker that died while processing a review leaves it running. Such
        records are returned to the queue after ``stale_after`` seconds.
        """
        now = time.time()
        with self._reviews_lock:
            records = self.list_reviews()
            for review in records:
                if review.get("status") == "running" and now - float(review.get("claimed_at") or 0) >= stale_after:
                    review.update({"status": "queued", "claimed_at": None, "updated": now, "error": None})
                    _atomic_write_json(self.review_path(review["review_id"]), review)
                    self._index_review_status(review)
            queued = [review for review in self.list_reviews() if review.get("status") == "queued"]
            if not queued:
                return None
            review = queued[-1]  # list is newest-first; claim oldest first
            review.update({"status": "running", "claimed_at": now, "updated": now, "error": None})
            _atomic_write_json(self.review_path(review["review_id"]), review)
            self._index_review_status(review)
            return review

    def record_review_template_if_unset(self, review_id: str, template: dict) -> dict:
        """Stamp the default note type on a review that was queued without one
        (the split/merge path, or records from before templates existed) when
        it is claimed, so the notes can always say which style produced them."""
        with self._reviews_lock:
            review = self._read_review_unlocked(review_id)
            if review is None or review.get("template_id"):
                return review or {}
            review.update(self._template_fields(template))
            _atomic_write_json(self.review_path(review_id), review)
            return review

    @staticmethod
    def _validated_review_payload(payload: dict) -> dict:
        if not isinstance(payload, dict):
            raise ValueError("review payload must be an object")
        try:
            encoded = json.dumps(payload, ensure_ascii=False)
            return json.loads(encoded)
        except (TypeError, ValueError) as exc:
            raise ValueError("review payload must contain only JSON values") from exc

    def complete_review(self, review_id: str, payload: dict) -> dict:
        with self._reviews_lock:
            review = self._read_review_unlocked(review_id)
            if review is None:
                raise ValueError(f"review does not exist: {review_id}")
            if review.get("status") not in ("queued", "running"):
                raise ValueError(f"review is not active: {review.get('status')}")
            payload = self._validated_review_payload(payload)
            title_override = review.get("title_override")
            if isinstance(title_override, str) and title_override.strip():
                payload["title"] = title_override
            review.update({
                "status": "done", "payload": payload,
                "completed_at": time.time(), "updated": time.time(), "error": None,
            })
            _atomic_write_json(self.review_path(review_id), review)
            self._index_review_status(review)
        self._notify("review_completed", review.get("session_id"))
        return review

    def rename_review(self, review_id: str, title: str) -> dict:
        """Update a user-edited meeting-summary title without changing its meeting."""
        _check_id(review_id, "review")
        with self._reviews_lock:
            review = self._read_review_unlocked(review_id)
            if review is None:
                raise ValueError(f"review does not exist: {review_id}")
            payload = review.get("payload")
            if not isinstance(payload, dict):
                raise ValueError("meeting notes are not available yet")
            payload = dict(payload)
            payload["title"] = title
            review.update({
                "payload": payload, "title_override": title, "updated": time.time()
            })
            _atomic_write_json(self.review_path(review_id), review)
            return review

    def fail_review(self, review_id: str, error: str) -> dict:
        with self._reviews_lock:
            review = self._read_review_unlocked(review_id)
            if review is None:
                raise ValueError(f"review does not exist: {review_id}")
            if review.get("status") not in ("queued", "running"):
                raise ValueError(f"review is not active: {review.get('status')}")
            review.update({"status": "error", "error": str(error), "updated": time.time()})
            _atomic_write_json(self.review_path(review_id), review)
            self._index_review_status(review)
            return review

    def retry_review(self, review_id: str, template: Optional[dict] = None) -> dict:
        """Re-queue a finished review; ``template`` switches its note type."""
        with self._reviews_lock:
            review = self._read_review_unlocked(review_id)
            if review is None:
                raise ValueError(f"review does not exist: {review_id}")
            if review.get("status") not in ("error", "done"):
                raise ValueError("only failed or completed reviews can be retried")
            review.update({
                "status": "queued", "claimed_at": None, "completed_at": None,
                "error": None, "payload": None, "updated": time.time(),
            })
            if template is not None:
                review.update(self._template_fields(template))
            _atomic_write_json(self.review_path(review_id), review)
            self._index_review_status(review)
            return review
