"""On-disk layout for the server: sessions' audio/timing/meta, and jobs.

Everything here is rooted at one directory (``MEETING_NOTES_DATA``, default
``/data`` -- the conventional mountpoint for the Docker volume). Session and
job ids arrive over the network (session ids from the recorder client, job ids
echoed back to it), so every id that becomes part of a filesystem path is
validated first: something like ``../../etc/passwd`` must never be able to
walk out of the data root.

Track audio is written with random-access seeks keyed by absolute frame
offset, not append-only, because the wire protocol is explicitly designed to
let a reconnecting client resend from its last acknowledged point without
regard for arrival order (see ``meeting_notes.wire``'s header comment). A
sidecar "ranges" file records which byte ranges of the ``.raw`` file have
actually been written (as opposed to being an unwritten hole that happens to
read back as zero, i.e. silence), so we can always answer "what is the
longest contiguous prefix received so far" -- that number is exactly what the
server acks, and what lets a resuming client know where to pick up.
"""

from __future__ import annotations

import json
import os
import re
import tempfile
import threading
import uuid
from pathlib import Path
from typing import List, Optional

from .. import wire

# Anything that isn't one path segment is rejected outright. Session and job
# ids are generated by us (uuid4 hex) or supplied by the recorder client, and
# either way they end up interpolated straight into filesystem paths, so this
# is the one gate that has to hold even against an actively hostile client.
_SAFE_ID = re.compile(r"^[A-Za-z0-9._-]+$")


def is_safe_id(value: str) -> bool:
    """True if ``value`` is safe to use as a single path component.

    Rejects empty strings, ``.``/``..``, anything containing a path separator
    (forward OR back slash -- this may run on a Windows dev box), and NUL,
    which some filesystems treat specially and Python otherwise reports a
    unicode error for.
    """
    if not value or value in (".", ".."):
        return False
    if "/" in value or "\\" in value or "\0" in value:
        return False
    return bool(_SAFE_ID.match(value))


class InvalidId(ValueError):
    """A session or job id failed path-safety validation."""


def _check_id(value: str, kind: str) -> str:
    if not is_safe_id(value):
        raise InvalidId(f"invalid {kind} id: {value!r}")
    return value


def resolve_data_root(data_root: Optional[str] = None) -> Path:
    """Pick the directory everything is stored under.

    Preference order: an explicit override (tests pass one so each test gets
    an isolated store), then ``MEETING_NOTES_DATA``, then ``/data`` (the
    Docker volume mountpoint). If that root can't actually be created/written
    to -- e.g. running this outside Docker with no ``/data`` and no
    permission to make it -- fall back to a temp directory rather than
    failing to start, so `pytest` and a bare `uvicorn` run locally both work
    with zero configuration.
    """
    candidate = data_root or os.environ.get("MEETING_NOTES_DATA") or "/data"
    path = Path(candidate)
    try:
        path.mkdir(parents=True, exist_ok=True)
        probe = path / f".write-probe-{os.getpid()}"
        probe.write_text("")
        probe.unlink()
        return path
    except OSError:
        fallback = Path(tempfile.mkdtemp(prefix="meeting-notes-data-"))
        return fallback


def _atomic_write_json(path: Path, payload) -> None:
    """Write JSON so a reader never sees a half-written file.

    The job worker thread and request handlers both touch job records
    concurrently; write-to-temp-then-rename makes every read see either the
    old content or the new content, never a torn mix of both.
    """
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp_name = tempfile.mkstemp(dir=str(path.parent), prefix=".tmp-", suffix=".json")
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as fh:
            json.dump(payload, fh, indent=2)
        os.replace(tmp_name, path)
    except BaseException:
        try:
            os.unlink(tmp_name)
        except OSError:
            pass
        raise


def _merge_ranges(ranges: List[List[int]], start: int, end: int) -> List[List[int]]:
    """Insert ``[start, end)`` into a sorted, merged list of half-open ranges."""
    if start >= end:
        return ranges
    out: List[List[int]] = []
    placed = False
    for lo, hi in ranges:
        if hi < start:
            out.append([lo, hi])
        elif end < lo:
            if not placed:
                out.append([start, end])
                placed = True
            out.append([lo, hi])
        else:
            # Overlaps or touches the new range -- merge instead of appending,
            # which is what makes writing the same offset twice (or two
            # adjacent chunks in either order) collapse into one interval
            # instead of accumulating duplicate/adjacent entries forever.
            start = min(start, lo)
            end = max(end, hi)
    if not placed:
        out.append([start, end])
    return out


def _contiguous_prefix(ranges: List[List[int]]) -> int:
    if ranges and ranges[0][0] == 0:
        return ranges[0][1]
    return 0


class Store:
    """Owns one data root and every read/write against it."""

    def __init__(self, data_root: Optional[str] = None):
        self.root = resolve_data_root(data_root)
        self.sessions_dir = self.root / "sessions"
        self.jobs_dir = self.root / "jobs"
        self.sessions_dir.mkdir(parents=True, exist_ok=True)
        self.jobs_dir.mkdir(parents=True, exist_ok=True)
        # One lock per (session, track) audio file, so writers of different
        # tracks/sessions never block each other, but the read-modify-write
        # cycle over a single track's ranges sidecar (below) can't race with
        # itself. A meeting has at most a handful of tracks, so a dict of
        # small locks is plenty -- no need for anything fancier.
        self._locks_guard = threading.Lock()
        self._locks: dict = {}
        self._jobs_lock = threading.Lock()

    # -- paths -----------------------------------------------------------

    def session_dir(self, session_id: str) -> Path:
        _check_id(session_id, "session")
        return self.sessions_dir / session_id

    def ensure_session_dir(self, session_id: str) -> Path:
        d = self.session_dir(session_id)
        d.mkdir(parents=True, exist_ok=True)
        return d

    def _track_track_check(self, track: str) -> str:
        # Tracks come from wire.TRACKS, a closed set, but still validate --
        # they land in a filename same as session/job ids do.
        return _check_id(track, "track")

    def track_raw_path(self, session_id: str, track: str) -> Path:
        return self.session_dir(session_id) / f"{self._track_track_check(track)}.raw"

    def track_wav_path(self, session_id: str, track: str) -> Path:
        return self.session_dir(session_id) / f"{self._track_track_check(track)}.wav"

    def track_timing_path(self, session_id: str, track: str) -> Path:
        return self.session_dir(session_id) / f"{self._track_track_check(track)}.timing.jsonl"

    def _ranges_path(self, session_id: str, track: str) -> Path:
        return self.session_dir(session_id) / f"{self._track_track_check(track)}.ranges.json"

    def session_meta_path(self, session_id: str) -> Path:
        return self.session_dir(session_id) / "session.json"

    def job_path(self, job_id: str) -> Path:
        _check_id(job_id, "job")
        return self.jobs_dir / f"{job_id}.json"

    def job_transcript_path(self, job_id: str) -> Path:
        _check_id(job_id, "job")
        return self.jobs_dir / f"{job_id}.transcript.json"

    # -- session meta ------------------------------------------------------

    def write_session_meta(self, session_id: str, meta: dict) -> None:
        self.ensure_session_dir(session_id)
        _atomic_write_json(self.session_meta_path(session_id), meta)

    def read_session_meta(self, session_id: str) -> dict:
        path = self.session_meta_path(session_id)
        if not path.exists():
            return {}
        return json.loads(path.read_text(encoding="utf-8"))

    def session_exists(self, session_id: str) -> bool:
        return self.session_dir(session_id).exists()

    # -- track audio ---------------------------------------------------------

    def _lock_for(self, session_id: str, track: str) -> threading.Lock:
        key = (session_id, track)
        with self._locks_guard:
            lock = self._locks.get(key)
            if lock is None:
                lock = threading.Lock()
                self._locks[key] = lock
            return lock

    def append_pcm(self, session_id: str, track: str, frame_offset: int, pcm: bytes) -> int:
        """Write ``pcm`` at ``frame_offset`` in this track's raw file.

        Returns the highest contiguous frame count from 0 -- i.e. what to ack.
        A write is a plain ``seek`` + ``write``, so re-sending the same offset
        (a reconnect resending unacknowledged data) or sending offsets out of
        order both land in the right place idempotently: writing identical
        bytes to the same range twice is a no-op as far as the *content* goes,
        and the ranges sidecar below (not file size) is what tracks how much
        of the file is real received audio versus an unwritten hole.
        """
        self._track_track_check(track)
        if frame_offset < 0:
            raise ValueError("frame_offset must not be negative")
        if len(pcm) % wire.BYTES_PER_FRAME:
            raise ValueError("pcm payload must contain whole int16 samples")
        n_frames = len(pcm) // wire.BYTES_PER_FRAME
        raw_path = self.track_raw_path(session_id, track)
        raw_path.parent.mkdir(parents=True, exist_ok=True)

        with self._lock_for(session_id, track):
            # 'r+b' needs the file to already exist; create it empty first.
            if not raw_path.exists():
                raw_path.touch()
            byte_offset = frame_offset * wire.BYTES_PER_FRAME
            with open(raw_path, "r+b") as fh:
                fh.seek(byte_offset)
                fh.write(pcm)

            ranges = self._read_ranges(session_id, track)
            if n_frames > 0:
                ranges = _merge_ranges(ranges, frame_offset, frame_offset + n_frames)
                self._write_ranges(session_id, track, ranges)
            return _contiguous_prefix(ranges)

    def contiguous_frames(self, session_id: str, track: str) -> int:
        return _contiguous_prefix(self._read_ranges(session_id, track))

    def read_pcm_range(self, session_id: str, track: str, start_frame: int, end_frame: int) -> bytes:
        """Read PCM for ``[start_frame, end_frame)``. Caller keeps this inside
        the acknowledged contiguous prefix -- there's no promise about what an
        unwritten hole beyond it contains."""
        if end_frame <= start_frame:
            return b""
        raw_path = self.track_raw_path(session_id, track)
        with self._lock_for(session_id, track):
            with open(raw_path, "rb") as fh:
                fh.seek(start_frame * wire.BYTES_PER_FRAME)
                return fh.read((end_frame - start_frame) * wire.BYTES_PER_FRAME)

    def _read_ranges(self, session_id: str, track: str) -> List[List[int]]:
        path = self._ranges_path(session_id, track)
        if not path.exists():
            return []
        try:
            return json.loads(path.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError):
            return []

    def _write_ranges(self, session_id: str, track: str, ranges: List[List[int]]) -> None:
        # Ranges are a JSON array, not an object, but _atomic_write_json only
        # cares that json.dump can serialize its argument -- it does.
        _atomic_write_json(self._ranges_path(session_id, track), ranges)

    # -- jobs ------------------------------------------------------------

    def create_job(self, session_id: str, settings: Optional[dict] = None) -> str:
        _check_id(session_id, "session")
        job_id = uuid.uuid4().hex
        record = {
            "job_id": job_id,
            "session_id": session_id,
            "settings": settings or {},
            "state": wire.JobState.QUEUED,
            "progress": 0.0,
            "error": None,
        }
        with self._jobs_lock:
            _atomic_write_json(self.job_path(job_id), record)
        return job_id

    def read_job(self, job_id: str) -> Optional[dict]:
        path = self.job_path(job_id)
        if not path.exists():
            return None
        try:
            return json.loads(path.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError):
            return None

    def update_job(self, job_id: str, **fields) -> None:
        with self._jobs_lock:
            record = self.read_job(job_id) or {"job_id": job_id}
            record.update(fields)
            _atomic_write_json(self.job_path(job_id), record)

    def write_transcript(self, job_id: str, markdown: str, json_text: str) -> None:
        _check_id(job_id, "job")
        _atomic_write_json(self.job_transcript_path(job_id), {"markdown": markdown, "json": json_text})

    def read_transcript(self, job_id: str) -> Optional[dict]:
        path = self.job_transcript_path(job_id)
        if not path.exists():
            return None
        try:
            return json.loads(path.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError):
            return None
